name: 'Release publisher'
description: 'Action to publish latest draft release'
author: "Allison Thackston"
branding:
  icon: "send"
  color: "yellow"
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
outputs:
  release_tag:
    description: "The tag that was published"
    value: ${{ steps.get_release_tag.outputs.release_tag }}
runs:
  using: 'composite'
  steps:
      - name: Get draft release tag
        id: get_release_tag
        shell: bash
        run: |
          # Fetch the list of draft releases from GitHub API
          response=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
                          "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100")

          # Extract the tag name of the first draft release (if any)
          release_tag=$(echo "$response" | jq -r '.[] | select(.draft == true) | .tag_name')
          if [ -z $release_tag ]; then
            echo "No release found"
          else
            echo "Found release draft tag $release_tag"
          fi
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

      - name: Publish release draft
        if: steps.get_release_tag.outputs.release_tag != ''
        shell: bash
        run: |
          gh release edit ${{ steps.get_release_tag.outputs.release_tag }} --draft=false
        env:
          GH_TOKEN: ${{ inputs.github_token }}
