name: Publish release draft

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Run if action manually triggered

permissions:
  contents: write # Needed to publish a draft release

env:
  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:

  publish-release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.publish_release_draft.outputs.release_tag }}
      latest_tag: ${{ steps.publish_release_draft.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }} # Needed to trigger release workflow
      - name: Release draft
        id: publish_release_draft
        uses: ./
