name: Publish release draft

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Run if action manually triggered

permissions:
  contents: write # Needed to publish a draft release

jobs:

  publish-release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.publish_release_draft.outputs.release_tag }}
      latest_tag: ${{ steps.publish_release_draft.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Release draft
        id: publish_release_draft
        uses: ./

  # Optional to run release workflow when released
  release-workflow:
    if: ${{ needs.publish-release.outputs.release_tag != ''}}
    needs: publish-release
    uses: athackst/publish-release-draft/.github/workflows/release.yml@main
