name: Release

on:
  release:
    types: [published] # Run if publish manually triggered
  workflow_dispatch: # Run if action manually triggered

permissions:
  contents: write

jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      # Post release steps
      - name: Post release steps
        run: echo "Post release steps"
