name: Release

on:
  release:
    types: [published] # Run if publish manually triggered
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Run if action manually triggered

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release_draft.outputs.release_tag }}
      latest_tag: ${{ steps.release_draft.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Release draft
        id: release_draft
        uses: ./

  readme:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.latest_tag != '' }}
    env:
      VERSION: ${{ needs.release.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Update readme.md
        run: |
          echo "Bumping version to ${VERSION}"
          bash .github/scripts/update_readme.sh ${VERSION}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "Update readme version"
          body: "Updates reame version to ${{ env.VERSION }}."
          branch: "skip/update-readme-${{ env.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' || needs.release.outputs.release_tag != '' }}
    needs: release
    runs-on: ubuntu-latest
    steps:
      # Post release steps
      - name: Post release steps
        run: echo "Post release steps"
