name: Draft release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5.25.0
        id: release-draft
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Update readme.md
        env:
          VERSION: ${{ steps.release-draft.outputs.tag_name }}
        run: |
          echo "Bumping version to ${VERSION}"
          bash .github/scripts/update_readme.sh ${VERSION}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "Update readme version"
          body: "Updates reame version to ${{ steps.release-draft.outputs.tag_name }}."
          branch: "skip/update-readme-${{ steps.release-draft.outputs.tag_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
